# Etapa 1: Compilar el proyecto
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: Ejecutar el microservicio
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/clientes-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
